logging:
   level:
     root: INFO
     sql: INFO
     com.haiercash: INFO

redis:
  cluster:
    timeout: 300000
    maxRedirections: 6
  pool:
    maxWaitMillis: -1
    maxTotal: 1000
    maxIdle: 9
    minIdle: 100
  #redis缓存数据超时时间
  expire:
    outTime: 2
    timeType: day
  cache:
    config:
      cacheArray:
        PL_CAPITAL_COOPERATION_AGENCY,
        PL_CAPITAL_AGENCY_DEMAND_INFO,
        PL_CAPITAL_AGENCY_DEMAND_ITEM,
        PL_CAPITAL_COOPERATION_PROJECT,
        PL_CAPITAL_BANK_INFO,
        PL_CAPITAL_PROJECT_BANK,
        PL_CAPITAL_COOPERATION_PERIOD,
        PL_CAPITAL_REPAYMENT_INFO,
        PL_CAPITAL_CASH_PRODUCT,
        PL_CAPITAL_INSERTS_CHANNEL,
        PL_CAPITAL_CASH_CUST_SIGN,
        PL_CAPITAL_DICTIONARY,
        PL_CAPITAL_DICTIONARY_SUB

spring:
  application:
    name: ${application.name}-${haiercash.pl.profile}
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1 from dual
    driverClassName: oracle.jdbc.OracleDriver
    platform: oracle
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 80
    initial-size: 10
    min-idle: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    converters:
      preferred-json-mapper: jackson # json 转换器, 接收数据和请求数据时使用
      preferred-xml-mapper: jackson # xml 转换器, 请求数据时使用
    encoding:
      force: true # 强制用 UTF-8 编码解析请求
    multipart:
      max-file-size: 10MB # 最大文件大小
      max-request-size: 10MB # 最大请求大小
  session:
    store-type: none

eureka:
  client:
      healthcheck.enabled: true
      register-with-eureka: true #是否注册自身到eureka服务器
      fetch-registry: true #是否从eureka服务器获取注册信息
      registryFetchIntervalSeconds: 5
      eurekaServiceUrlPollIntervalSeconds: 120
  instance:
    instance-id: ${spring.application.name}@${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}(${spring.cloud.client.hostname}-[version:${application.version}])
    hostname: localhost
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    securePortEnabled: false

ribbon:
  ConnectTimeout: 300000
  ReadTimeout: 600000
  MaxTotalHttpConnections: 5000
  MaxHttpConnectionsPerHost: 5000
  ActiveConnectionsLimit: 5000
  eureka:
    enabled: true

management.security.enabled: false

mybatis:
  dialect: com.haiercash.pluslink.capital.common.mybatis.dialect.OracleDialect

log:
  action:
    open: true
    table: PL_ROUTER_API_LOG

api:
  code:
    #错误的服务名称
    method-not-found: PLCR0001
    #未知异常
    system-error: 99999
    infos:
      success:
        status: S
        code: 00000
        message: 处理成功！

jasypt:
  encryptor:
    password: 123456