--银行信息表初始化数据
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('delxLROPVWujPUodtQu', '上海银行', 'BOS', '04012900', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('ciGjgMEGGVZv92ZQHIP', '北京银行', 'BOB', '04031000', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('IG5eCYuXgUWOFoxwBfJ', '工商银行', 'ICBC', '102', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('gGOpNpguvrAwiW4UxQp', '农业银行', 'ABC', '103', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('S1Yde301Znis8qNUDlr', '中国银行', 'BOC', '104', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('4ZHhePpNuoeS86gfQGu', '建设银行', 'CCB', '105', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('SQqts0bs0o2gyB4K206', '交通银行', 'BCM', '301', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('gDl4mqw9TI6FxZnrhSz', '光大银行', 'CEB', '303', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('NJazsmSMefoeKs278rZ', '华夏银行', 'HXB', '304', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('5CIlih4sWBrbGSwga3g', '广发银行', 'CGB', '306', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('REx9dOzKXK5Fr5BtugF', '平安银行', 'PAB', '307', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('derdPLb7jYcG4rGwFBj', '招商银行', 'CMB', '308', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('iOx1hmI8ABCt4rJ6Bhj', '兴业银行', 'CIB', '309', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('SM0arUf68YDwNroUed3', '浦发银行', 'SPDB', '310', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
insert into PL_BANK_INFO (ID, BANK_NAME, BANK_NO_EN, BANK_NO_NUM, CREATE_DATE, UPDATE_DATE, CREATE_BY, DEL_FLAG) values ('5TslBKcHqccChmRMXcC', '邮储银行', 'PSBC', '403', SYSDATE, SYSDATE, 'SYSTEM', 'NORMAL');
