--路由结果表:业务编号
create INDEX IND_ROUTE_RESULT_RECORD on PL_ROUTE_RESULT_RECORD (APPL_SEQ);--tablespace XPAD_SXJ_IDX

--处理中心任务
create INDEX IND_PROCESSER_JOB_MODEL_NAME on PL_PROCESSER_JOB (MODEL_NAME);
create INDEX IND_PROCESSER_JOB_STATUS on PL_PROCESSER_JOB (JOB_STATUS);
create INDEX IND_PROCESSER_JOB_DEL_FLAG on PL_PROCESSER_JOB (DEL_FLAG);
create INDEX IND_PROCESSER_JOB_START_DATE on PL_PROCESSER_JOB (JOB_START_DATE);

--处理中心放款记录
create INDEX IND_PROCESSER_MAKE_LOANS_SEQ on PL_PROCESSER_MAKE_LOANS (APPL_SEQ);
create INDEX IND_MAKE_LOANS_DEL_FLAG on PL_PROCESSER_MAKE_LOANS (DEL_FLAG);
create INDEX IND_MAKE_SPLIT_ID on PL_PROCESSER_MAKE_LOANS (ASSETS_SPLIT_ID);

--处理中心额度
create INDEX IND_MAKE_SPLIT_ITEM_ID on PL_PROCESSER_MAKE_LOANS (ASSETS_SPLIT_ITEM_ID);

--处理中心资产
create INDEX IND_ASSETS_SPLIT_APPL_SEQ on PL_ASSETS_SPLIT (APPL_SEQ);
create INDEX IND_ASSETS_SPLIT_APPL_DEL_FLAG on PL_ASSETS_SPLIT (DEL_FLAG);
create INDEX IND_SPLIT_CONTRACT_NO on PL_ASSETS_SPLIT (CONTRACT_NO);

--处理中心资产明细
create INDEX IND_ASSETS_SPLIT_ITEM_MAIN_ID on PL_ASSETS_SPLIT_ITEM (ASSETS_SPLIT_ID);
create INDEX IND_ASSETS_SPLIT_DEL_FLAG on PL_ASSETS_SPLIT_ITEM (DEL_FLAG);
create INDEX IND_ASSETS_SPLIT_LOAN_NO on PL_ASSETS_SPLIT_ITEM (LOAN_NO);

--处理中心日志
create INDEX IND_ROUTER_API_LOG_KEY on PL_ROUTER_API_LOG (FD_KEY);
--前置日志
create INDEX IND_PROCESSER_API_LOG_KEY on PL_PROCESSER_API_LOG (FD_KEY);
--路由日志
create INDEX IND_PREPOSITION_API_LOG_KEY on PL_PREPOSITION_API_LOG (FD_KEY);

--任务表索引
create INDEX IND_PROCESSER_JOB_RUN_TIME on PL_PROCESSER_JOB (FD_KEY);

alter table PL_ASSETS_SPLIT add constraint UNIQUE_APPL_SEQ unique (APPL_SEQ);
create INDEX IND_ASSETS_SPLIT_LOAN_STATUS on PL_ASSETS_SPLIT (LOAN_STATUS);
create INDEX IND_ASSETS_SPLIT_STATUS on PL_ASSETS_SPLIT_ITEM (STATUS);