#功能测试验证环境配置
haiercash:
  pl:
    profile: beta

server:
  port: 7897

redis:
  cluster:
    address: 10.164.197.209:7000,10.164.197.208:7000,10.164.197.202:7000

spring:
  datasource:
    url: jdbc:oracle:thin:@10.164.204.106:1521/plloandb
    username: plloan
    password: ENC(pdGVKsdhGvySQuIs3sNEjA==)

eureka:
  client:
      serviceUrl:
        defaultZone: http://10.164.197.208:1180/eureka/,http://10.164.197.209:1180/eureka/

rest:
  controller:
    instance:
      lastLoanQuery: ACRM